# SITE CONFIGURATION
title: Marcio Ribeiro # your site title
author: marciovai # You :P
description: > # Meta description of Homepage
  I'm a Software Engineer and Data Scientist based in São Paulo, Brazil. This
  blog is a place for me to share ideas and things I've done, some of
  my topics of interest include Machine Learning applied to Computer Graphics 
  and Game Development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Marcio Ribeiro
  links:
    - https://twitter.com/marciovai
    - https://www.linkedin.com/in/marciorib
    - https://github.com/marciovai

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Software is never finished, only released

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: marcioribp@gmail.com # email for form submission

twitter_username: marciovai # replace with your_twitter_username or comment to remove link from footer
github_username:  marciovai # replace with your_github_username or comment to remove link from footer
# instagram_username: marciovai # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: disqus_3ZMS2RTAd0 # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
